version: "3.3"

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=app_store-db
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ../postgres_data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@mail.com
  #     - PGADMIN_DEFAULT_PASSWORD=root
  #   ports:
  #     - 5050:80

  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - postgres
    command: dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/usr/src
      ## Nest line prevents to over write and delete node_module container folder
      - /usr/src/node_modules
    links:
      - postgres
